# Generated by Django 5.1.7 on 2025-03-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='guest_id',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='loyalty_points',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='special_requests',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='vip_status',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('housekeeping', 'Housekeeping'), ('guest', 'Guest')], default='guest', max_length=20),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
